### ISSUE TITLE
Python parser doesn't recognize URI's

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/grammar#9]
**`shexc_to_shexj http://hl7.org/fhir/observation.shex`**

```
Traceback (most recent call last):
  File "/Users/solbrig/pyvenv/foo/bin/shexc_to_shexj", line 9, in <module>
    generate(sys.argv[1:])
  File "/Users/solbrig/pyvenv/foo/lib/python3.7/site-packages/pyshexc/parser_impl/generate_shexj.py", line 133, in generate
    if do_parse(opts.infile, opts.jsonfile, opts.rdffile, opts.format, opts.context):
  File "/Users/solbrig/pyvenv/foo/lib/python3.7/site-packages/pyshexc/parser_impl/generate_shexj.py", line 43, in do_parse
    shexj = parse(FileStream(infilename, encoding="utf-8"))
  File "/Users/solbrig/pyvenv/foo/lib/python3.7/site-packages/antlr4/FileStream.py", line 20, in __init__
    super().__init__(self.readDataFrom(fileName, encoding, errors))
  File "/Users/solbrig/pyvenv/foo/lib/python3.7/site-packages/antlr4/FileStream.py", line 25, in readDataFrom
    with open(fileName, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'http://hl7.org/fhir/observation.shex'
```

**Comment by ericprud** [comment]
closable?
